# Generated by Django 3.1.3 on 2020-12-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.colleges')),
            ],
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.categories'),
        ),
    ]
