# Generated by Django 3.1.3 on 2021-01-19 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_status', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.categories')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.colleges')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.fooditems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user')),
            ],
        ),
    ]
